# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe("/cultures", type: :request) do
  # This should return the minimal set of attributes required to create a valid
  # Culture. As you add validations to Culture, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Culture.create!(valid_attributes)
      get cultures_url
      expect(response).to(be_successful)
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      culture = Culture.create!(valid_attributes)
      get culture_url(culture)
      expect(response).to(be_successful)
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_culture_url
      expect(response).to(be_successful)
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      culture = Culture.create!(valid_attributes)
      get edit_culture_url(culture)
      expect(response).to(be_successful)
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Culture" do
        expect {
          post(cultures_url, params: { culture: valid_attributes })
        }.to(change(Culture, :count).by(1))
      end

      it "redirects to the created culture" do
        post cultures_url, params: { culture: valid_attributes }
        expect(response).to(redirect_to(culture_url(Culture.last)))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Culture" do
        expect {
          post(cultures_url, params: { culture: invalid_attributes })
        }.to(change(Culture, :count).by(0))
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post cultures_url, params: { culture: invalid_attributes }
        expect(response).to(have_http_status(:unprocessable_entity))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested culture" do
        culture = Culture.create!(valid_attributes)
        patch culture_url(culture), params: { culture: new_attributes }
        culture.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the culture" do
        culture = Culture.create!(valid_attributes)
        patch culture_url(culture), params: { culture: new_attributes }
        culture.reload
        expect(response).to(redirect_to(culture_url(culture)))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        culture = Culture.create!(valid_attributes)
        patch culture_url(culture), params: { culture: invalid_attributes }
        expect(response).to(have_http_status(:unprocessable_entity))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested culture" do
      culture = Culture.create!(valid_attributes)
      expect {
        delete(culture_url(culture))
      }.to(change(Culture, :count).by(-1))
    end

    it "redirects to the cultures list" do
      culture = Culture.create!(valid_attributes)
      delete culture_url(culture)
      expect(response).to(redirect_to(cultures_url))
    end
  end
end
