default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: senamiranda
  host: localhost
  port: 5432

development:
  <<: *default
  database: agro_manager_development

test:
  <<: *default
  database: agro_manager_test

production:
  primary: &primary_production
    <<: *default
    database: agro_manager_production
    username: agro_manager
    password: <%= ENV["AGRO_MANAGER_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: agro_manager_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: agro_manager_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: agro_manager_production_cable
    migrations_paths: db/cable_migrate
